### ISSUE TITLE
`account` Subcommand

### ISSUE THREAD

**Issue by cavemanloverboy** [cavemanloverboy/sol#1]
Would love to add account explorer support. You pass in account pubkey, you learn about it.

`sol account <PUBKEY>` 

This should do some minimal parsing for known programs such as system accounts, token accounts, etc.

For all others, should just show:

1) program owner
2) data (base58 or base64, perhaps with zstd compression)
3) lamports

**Comment by cavemanloverboy** [comment]
This may be an incomplete list of wanted features. Feel free to suggest more.

**Comment by arihantbansal** [comment]
I'd like to work on this.

**Comment by cavemanloverboy** [comment]
> I'd like to work on this.

🫡

**Comment by cavemanloverboy** [comment]
any updates on this @arihantbansal

**Comment by arihantbansal** [comment]
> any updates on this @arihantbansal

Will make a draft PR today. Wanted to get your thoughts on parsing account data.

**Comment by cavemanloverboy** [comment]
any updates here?

**Comment by cavemanloverboy** [comment]
closed by #6
